### ISSUE TITLE
Сделать таблицу, в которой жёстко задать значения Статусов Таска

### ISSUE THREAD

**Issue by alekseyl1992** [iu5team/rms#10]
Это требуется для разделения тасков на done / undone.
То есть как минимум должен быть статус "done".

**Comment by alekseyl1992** [comment]
нафиг
это усложнит самописные SQL-запросы
просто помните - для закрытия таска надо написать именно строку "done"
и никак иначе

**Comment by igorcoding** [comment]
по хорошему - лучше кнопку сделать (Done)

**Comment by IvanGamazov** [comment]
Согласен про кнопку

вторник, 26 апреля 2016 г. пользователь igorcoding написал:
