### ISSUE TITLE
IndexError при рисовании графика ресурса, когда нет тасков.

### ISSUE THREAD

**Issue by igorcoding** [iu5team/rms#21]
Создал ного юзера, попытался нарисовать график, получил Exception

```
app/views/employee.py in form_valid
        context['graphic'] = plot_tasks(tasks, date_from, date_to) ...
app/views/employee.py in plot_tasks
    counts, bins, patches = ax.hist(days, bins=duration, range=(1, duration), histtype='stepfilled') ...
python/matplotlib/axes.py in hist
        if isinstance(x, np.ndarray) or not iterable(x[0]): ...
```

**Comment by alekseyl1992** [comment]
проверил
по твоему описанию не воспроизводится

зато падает, если указать from == to
вероятно именно это ты и сделал

**Comment by alekseyl1992** [comment]
само исключение:
Exception Type: AttributeError
Exception Value:  
max must be larger than min in range parameter.

**Comment by alekseyl1992** [comment]
не воспроизвелось - и хер с ним
с датами тоже хер
